export const FORM_LOADING = "FORM_LOADING";
export const FORM_SUBMITTING = "FORM_SUBMITTING";
export const FORM_PROGRESS = "FORM_PROGRESS";
export const FORM_DEFINITION = "FORM_DEFINITION";
export const SET_FORM_VALUE = "SET_FORM_VALUE";
export const RESET_FORM_VALUES = "RESET_FORM_VALUES";
export const FORM_SOURCE = "FORM_SOURCE";
